In [109]:
import os
from pathlib import Path
import pandas as pd

# defining paths for notebook
current_dir = Path(globals()["_dh"][0])

raw_data_path = os.path.join(current_dir, r"..\..\raw(bronze)")
processed_data_path = os.path.join(current_dir, "athletes_per_gender.csv")
parquet = os.path.join(current_dir, "athletes_per_gender.parquet")

In [ ]:
df_all_path = os.path.join(raw_data_path, "athletes_history.csv")
df_all = pd.read_csv(df_all_path)

In [ ]:
df_paris_path = os.path.join(raw_data_path, "athletes_paris.csv")
df_paris = pd.read_csv(df_paris_path)

# Processing Dataframes

## Processing athletes history

In [100]:
df1 = df_all["sex"].value_counts()
df1 = pd.DataFrame([df1]).T
df1.index.names = ["gender"]
df1.head()

         count
gender
Male    115527
Female   40334

In [101]:
df_all = df1

## Processing athletes in Paris 2024

In [102]:
df2 = df_paris["gender"].value_counts()
df2 = pd.DataFrame([df2]).T
df2.head()

        count
gender
Male     5658
Female   5455

In [103]:
df_paris = df2

## Merging DataFrames

In [105]:
df_final = pd.concat([df_all, df_paris])
df_final = df_final.groupby(["gender"]).sum()
df_final.head()

         count
gender
Female   45789
Male    121185

## Saving files

In [110]:
df_final.to_csv(processed_data_path)
df_final.to_parquet(parquet, index=False, engine="fastparquet")